=== CameronSten/COMP4711Lab7/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT schedule (days)>
<!ATTLIST schedule term (1|2|3|4) #REQUIRED>

<!ELEMENT days (weekday)*>

<!ELEMENT weekday (classinfo)*>
<!ATTLIST weekday day (monday|tuesday|wednesday|thursday|friday) #REQUIRED>

<!ELEMENT classinfo (type, buidling, room, instructor, time?, class?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT class (#PCDATA)>

<!ELEMENT timeblock (classinfo)*>
<!ATTLIST timeblock classtime (8:30|9:30|10:30|11:30|12:30|13:30|14:30|15:30|16:30)>

<!ELEMENT course (classinfo)*>
<!ATTLIST course coursenumber (4995|4932|4711|4735|4560|3600)>

=== CameronSten/COMP4711Lab7/data/day.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "schedule.dtd">

<schedule term="4">
	<days>
		<weekday day="monday">
			<classinfo>
                                <type>lecture</type>
				<building>SE-12</building>
                                <room>308</room>
				<instructor>Dennis Richards</instructor>
				<time>8:30</time>
				<class>COMP4932</class>
			</classinfo>
			<classinfo>
                                <type>lecture</type>
				<building>SW-1</building>
				<room>1205</room>
				<instructor>Mirela Gutica</instructor>
				<time>11:30</time>
				<class>COMP4735</class>
			</classinfo>
			<classinfo>
                                <type>lab</type>
				<building>SE-12</building>
				<room>308</room>
				<instructor>Dennis Richards</instructor>
				<time>14:30</time>
				<class>COMP4995</class>
			</classinfo>
		</weekday>
	    <weekday day="tuesday">
	        <classinfo>
                    <type>lab</type>
	            <building>SE-12</building>
	            <room>320</room>
	            <instructor>Brenda Fine</instructor>
	            <time>9:30</time>
	            <class>COMP4560</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SW-5</building>
	            <room>1850</room>
	            <instructor>Brenda Fine</instructor>
	            <time>11:30</time>
	            <class>COMP4560</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SW-5</building>
	            <room>1840</room>
	            <instructor>James Parry</instructor>
	            <time>14:30</time>
	            <class>COMP4711</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <time>15:30</time>
	            <class>COMP4932</class>
	        </classinfo>
	    </weekday>
	    <weekday day="wednewday">
	        <classinfo>
                    <type>lab</type>
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Matthew Linder</instructor>
	            <time>8:30</time>
	            <class>COMP4735</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <time>10:30</time>
	            <class>COMP4995</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SE-1</building>
	            <room>1205</room>
	            <instructor>Mirela Gutica</instructor>
	            <time>13:30</time>
	            <class>COMP4735</class>
	        </classinfo>
	    </weekday>
	    <weekday day="thursday">
	        <classinfo>
                    <type>lecture</type>
	            <building>SW-3</building>
	            <room>1710</room>
	            <instructor>Mirela Gutica</instructor>
	            <time>11:30</time>
	            <class>COMP4735</class>
	        </classinfo>
	        <classinfo>
                    <type>lab</type>
	            <building>Sw-3</building>
	            <room>4725</room>
	            <instructor>Catherine Ryan</instructor>
	            <time>13:30</time>
	            <class>BLAW3600</class>
	        </classinfo>
	        <classinfo>
                    <type>lab</type>
	            <building>SE-12</building>
	            <room>310</room>
	            <instructor>James Parry</instructor>
	            <time>15:30</time>
	            <class>COMP4711</class>
	        </classinfo>
	    </weekday>
	    <weekday day="friday">
	        <classinfo>
                    <type>lecture</type>
	            <building>SW-5</building>
	            <room>1840</room>
	            <instructor>Catherine Ryan</instructor>
	            <time>8:30</time>
	            <class>BLAW3600</class>
	        </classinfo>
	        <classinfo>
                    <type>lecture</type>
	            <building>SW-3</building>
	            <room>1750</room>
	            <instructor>Brenda Fine</instructor>
	            <time>12:30</time>
	            <class>COMP4560</class>
	        </classinfo>
	    </weekday>
	</days>
</schedule>
